trainer_params:
  fast_dev_run: False
model_params:
  face_comparer_params:
    hidden_dims: []
    initial_bias: -65
    feature_extractor_model: 'arcface'
    feature_normalization_mode: 3
    feature_normalization_scale: 0.1
    feature_extractor_params:
      model_path: 'InsightFace_v2/checkpoint_full.tar'
  milestones: [-1, -1]
checkpoint_params:
  save_last: True
  filepath: 'saved_models/arcface_latest'